### ISSUE TITLE
Brak wsparcia dla django 1.8

### ISSUE THREAD

**Issue by ad-m** [scibi/django-teryt#6]
Zwykły ````python manage.py teryt_parse TERC.xml SIMC.xml ``` zgłasza wyjątek:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/adas/.virtualenvs/feder/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/adas/.virtualenvs/feder/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/adas/.virtualenvs/feder/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 190, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/adas/.virtualenvs/feder/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/adas/.virtualenvs/feder/local/lib/python2.7/site-packages/teryt/management/commands/teryt_parse.py", line 15, in <module>
    class Command(BaseCommand):
  File "/home/adas/.virtualenvs/feder/local/lib/python2.7/site-packages/teryt/management/commands/teryt_parse.py", line 26, in Command
    @transaction.commit_manually
AttributeError: 'module' object has no attribute 'commit_manually'

````

Dlaczego? Dekorator został usunięty ( https://github.com/django/django/blob/master/docs/releases/1.8.txt ).

**Comment by scibi** [comment]
Tak wiem. Planuję refactoring tego kodu i dodanie testów. Postaram się w okolicach weekendu znaleźć czas by to ogarnąć. Jak pilnie potrzeba to mogę na razie puścić jakąś wersję, która tylko poprawia ten problem.
